#!/bin/bash

# This INIT INFO block is required, per
#   http://wiki.debian.org/LSBInitScripts

### BEGIN INIT INFO
# Provides:          cyclopath-mr_do
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# To install:
#   sudo mv -f cyclopath-mr_do /etc/init.d/
#   sudo chmod 755 /etc/init.d/cyclopath-mr_do
#   sudo chown root /etc/init.d/cyclopath-mr_do
#   sudo chgrp root /etc/init.d/cyclopath-mr_do
#   sudo update-rc.d cyclopath-mr_do defaults

cd /ccp/dev/cp/services

#sudo -u www-data INSTANCE=minnesota \
#   PYTHONPATH=/ccp/opt/usr/lib/python:/ccp/opt/usr/lib/PYTHONVERS2()/site-packages:/ccp/opt/gdal/lib/PYTHONVERS2()/site-packages \
#   PYSERVER_HOME=/ccp/dev/cp/pyserver ./mr_doctl $@

su -c "INSTANCE=minnesota \
   PYTHONPATH=/ccp/opt/usr/lib/python:/ccp/opt/usr/lib/PYTHONVERS2()/site-packages:/ccp/opt/gdal/lib/PYTHONVERS2()/site-packages \
   PYSERVER_HOME=/ccp/dev/cp/pyserver ./mr_doctl $@" www-data

# NOTE: Not starting Mr. Do! for other INSTANCEs, i.e., colorado.
