#!/usr/bin/perl

# Copyright (c) 2006-2013 Regents of the University of Minnesota.
# For licensing terms, see the file LICENSE.

# This can output both Python and MXML.

use strict;
use warnings;

use POSIX;

#my $now = POSIX::strftime('%Y%m%d.%H%M%S', gmtime());
# CURIOUS: [lb] What is this chopping?
# chop($now); # two builds in 10 seconds seems unlikely
# NOTE Using GMT, not local time (CST or CDT)
my $now = POSIX::strftime('%Y/%m/%d.%H:%M', gmtime());
my $nowdate = POSIX::strftime('%b %d, %Y', gmtime());
my $date_abbrev = POSIX::strftime('%y.%m.%d', gmtime());

`svn info | grep URL` =~ m|/([^/]+?)/flashclient$|;
my $branch = $1 || 'not_a_working_copy';

if ($ARGV[0] eq '--date') {
   # parens... LAME (FIXME)
   print <<EOF;
<mx:Label 
   xmlns:mx="http://www.adobe.com/2006/mxml"
   xmlns="*"
   text="($nowdate)">
</mx:Label>
EOF
}
elsif ($ARGV[0] eq '--mxml') {
   print <<EOF;
<mx:HBox 
   xmlns:mx="http://www.adobe.com/2006/mxml"
   xmlns="*"
   horizontalGap="0">
   <mx:Label
      id="version_label"
      fontSize="8"
      text="Client version:"/>
   <mx:Label
      id="major"
      fontSize="8"
      text="$branch"/>
   <views_panel_util:Help_Link
      click_url="/Release_Notes"
      text="What's New?"
      paddingRight="-5"/>
   <mx:Label
      id="now_label"
      fontSize="8"
      text="[$now]"/>
</mx:HBox>
EOF
}
elsif ($ARGV[0] eq '--info') {
   # FIXME Should this info go in the Control Panel 
   #        or something (and not on the landing screen)
   print <<EOF;
package {
   public class BUILD_INFO {
      public static const major:String = '$branch';
      public static const now:String = '$now';
      public static const nowdate:String = '$nowdate';
      public static const date_abbrev:String = '$date_abbrev';
   }
}
EOF
}
elsif ($ARGV[0] eq '--python') {
   print <<EOF;
# Automatically generated by build_id.pl. Do not edit.
major = '$branch'
EOF
}
else {
   die 'usage error';
}

